// ==UserScript==
// @name         Peakmonsters Rental Filters
// @description  Simple tampermonkey script to filter cards on CP and get best options to buy
// @namespace    https://github.com/breakerh/peakmonsters-filter
// @version      0.0.1
// @author       @breakerh
// @match        https://peakmonsters.com/rentals
// @icon         https://www.google.com/s2/favicons?domain=peakmonsters.com
// @updateURL    https://raw.githubusercontent.com/breakerh/peakmonsters-filter/main/peakmonsters-filter.js
// @downloadURL  https://raw.githubusercontent.com/breakerh/peakmonsters-filter/main/peakmonsters-filter.js
// @grant        none
// @run-at       document-end
// ==/UserScript==

(function() {
    'use strict';

    const cardNames = [
        null,
        "Goblin Shaman",
        "Giant Roc",
        "Kobold Miner",
        "Fire Beetle",
        "Malric Inferno",
        "Serpentine Soldier",
        "Pit Ogre",
        "Cerberus",
        "Fire Demon",
        "Serpent of the Flame",
        "Elemental Phoenix",
        "Pirate Captain",
        "Spineback Turtle",
        "Crustacean King",
        "Sabre Shark",
        "Alric Stormbringer",
        "Medusa",
        "Water Elemental",
        "Frozen Soldier",
        "Mischievous Mermaid",
        "Naga Warrior",
        "Frost Giant",
        "Flesh Golem",
        "Goblin Sorcerer",
        "Rexxie",
        "Minotaur Warrior",
        "Lyanna Natura",
        "Earth Elemental",
        "Stone Golem",
        "Stonesplitter Orc",
        "Magi of the Forest",
        "Swamp Thing",
        "Spirit of the Forest",
        "Divine Healer",
        "Feral Spirit",
        "Silvershield Knight",
        "Silvershield Warrior",
        "Tyrus Paladium",
        "Peacebringer",
        "Silvershield Paladin",
        "Clay Golem",
        "Defender of Truth",
        "Air Elemental",
        "Angel of Light",
        "Animated Corpse",
        "Haunted Spider",
        "Skeleton Assassin",
        "Spineback Wolf",
        "Zintar Mortalis",
        "Haunted Spirit",
        "Twisted Jester",
        "Undead Priest",
        "Dark Enchantress",
        "Screaming Banshee",
        "Lord of Darkness",
        "Selenia Sky",
        "Lightning Dragon",
        "Chromatic Dragon",
        "Gold Dragon",
        "Peaceful Giant",
        "Grumpy Dwarf",
        "Elven Cutthroat",
        "Centaur",
        "Cocatrice",
        "Cyclops",
        "Enchanted Pixie",
        "Raging Impaler",
        "Magi Sphinx",
        "Hydra",
        "Talia Firestorm",
        "Xia Seachan",
        "Xander Foxwood",
        "Kiara Lightbringer",
        "Jarlax the Undead",
        "Dragon Whelp",
        "Royal Dragon Archer",
        "Shin-Lo",
        "Neb Seni",
        "Highland Archer",
        "Rusty Android",
        "Hobgoblin",
        "Lord Arianthus",
        "Sea Genie",
        "Divine Sorceress",
        "Mushroom Seer",
        "Vampire",
        "Flame Imp",
        "Daria Dragonscale",
        "Sacred Unicorn",
        "Wood Nymph",
        "Creeping Ooze",
        "Phantom Soldier",
        "Pirate Archer",
        "Naga Fire Wizard",
        "Brownie",
        "Silvershield Archers",
        "Goblin Mech",
        "Ruler of the Seas",
        "Skeletal Warrior",
        "Imp Bowman",
        "Crystal Werewolf",
        "Javelin Thrower",
        "Sea Monster",
        "Prismatic Energy",
        "Undead Minotaur",
        "Exploding Dwarf",
        "Manticore",
        "Black Dragon",
        "Crypt Mancer",
        "Plado Emberstorm",
        "Valnamor",
        "Prince Rennyn",
        "The Peakrider",
        "Delwyn Dragonscale",
        "Dragonling Bowman",
        "Fiendish Harpy",
        "Red Dragon",
        "Armorsmith",
        "Silvershield Bard",
        "Goblin Chef",
        "Minotaur Warlord",
        "Electric Eels",
        "Mermaid Healer",
        "Undead Archer",
        "Corrupted Pegasus",
        "Molten Ogre",
        "Lord of Fire",
        "Enchanted Defender",
        "Dwarven Wizard",
        "Archmage Arius",
        "Furious Chicken",
        "Fallen Specter",
        "Beetle Queen",
        "Naga Windmaster",
        "Maggots",
        "Cursed Slimeball",
        "Giant Scorpion",
        "Undead Badger",
        "Dark Astronomer",
        "Bone Golem",
        "Death Elemental",
        "Soulstorm",
        "Darkest Mage",
        "Dark Ha'on",
        "Contessa L'ament",
        "Cave Slug",
        "Crystal Jaguar",
        "Lone Boatman",
        "Herbalist",
        "Truthspeaker",
        "Luminous Eagle",
        "Shieldbearer",
        "Light Elemental",
        "Thunderbird",
        "High Priest Darius",
        "Mother Khala",
        "Kobold Bruiser",
        "Serpentine Spy",
        "Magma Troll",
        "Goblin Fireballer",
        "Fire Elemental",
        "Living Lava",
        "Spark Pixies",
        "Ferexia General",
        "Pyromaniac",
        "Magnor",
        "Pyre",
        "Feasting Seaweed",
        "Albatross",
        "Tortisian Fighter",
        "Sniping Narwhal",
        "Ice Pixie",
        "Giant Squid",
        "Serpent of Eld",
        "Coral Wraith",
        "Azmare Harpoonist",
        "Phantom of the Abyss",
        "Bortus",
        "Goblin Thief",
        "Failed Summoner",
        "Biceratops",
        "Orc Sergeant",
        "Khmer Princess",
        "Unicorn Mustang",
        "Child of the Forest",
        "Mitica Headhunter",
        "Sporcerer",
        "Kron the Undying",
        "Wizard of Eastwood",
        "Elven Defender",
        "Horny Toad",
        "Mantoid",
        "Parasitic Growth",
        "Elven Mystic",
        "Goblin Chariot",
        "Tower Griffin",
        "War Chaang",
        "Tortisian Chief",
        "Cornealus",
        "Camila Sungazer",
        "The Vigilator",
        "Scale Doctor",
        "Dragon Jumper",
        "Gloridax Magus",
        "Prince Julian",
        "Boogeyman",
        "Spirit Miner",
        "Battle Orca",
        "Chain Golem",
        "Diamond Dragon",
        "Gloridax Guardian",
        "Fire Spitter",
        "The Kraken",
        "Ettin Spearman",
        "Octopider",
        "Silvershield Assassin",
        "Baby Unicorn",
        "Gelatinous Cube",
        "Gremlin Blaster",
        "Screeching Vulture",
        "Spirit Shaman",
        "Zalran Efreet",
        "Serpentine Mystic",
        "Drake of Arnak",
        "Barking Spider",
        "Nectar Queen",
        "Flame Monkey",
        "Pyromancer",
        "Undead Rexx",
        "Shadowy Presence",
        "Torhilo the Frozen",
        "Wave Runner",
        "Warrior of Peace",
        "Evangelist",
        "Mimosa Nightshade",
        "Yodin Zaku",
        "Halfling Alchemist",
        "Mighty Dricken",
        "Chanseus the Great",
        "Kretch Tallevor",
        "Onyx Sentinel",
        "Sand Worm",
        "Silvershield Sheriff",
        "Bila the Radiant",
        "Grim Reaper",
        "Phantasm",
        "Fineas Rage",
        "Ant Miners",
        "Spirit Druid Grog",
        "Captain's Ghost",
        "Kelp Initiate",
        "Gloridax Soldier",
        "Centauri Mage",
        "Lir Deepswimmer",
        "Robo-Dragon Knight",
        "Ancient Lich",
        "Vera Salacia",
        "Owster Rotwell",
        "Mylor Crowling",
        "Qid Yuff",
        "Lorna Shine",
        "Brighton Bloom",
        "Poseidon",
        "Frost Lion",
        "Caladuum",
        "Flamesmith",
        "Cthulhu",
        "Marrow's Ghost",
        "Kralus",
        "Lunakari Mistress",
        "Oaken Behemoth",
        "Goblin Dartling",
        "Battering Ram",
        "Naga Brute",
        "Dragon Spirit",
        "Grenadier",
        "Lensmaster",
        "Scarred Llama Mage",
        "Beatrix Ironhand",
        "Axemaster",
        "Charlok Minotaur",
        "Dark Ferryman",
        "Chain Spinner",
        "Harvester",
        "Nightmare",
        "Almo Cambio",
        "Demented Shark",
        "Temple Priest",
        "Efreet Elder",
        "Theorosa Nightshade",
        "Byzantine Kitty",
        "Goblin Firemage",
        "Lobstradamus",
        "The Gorlodon",
        "Hero of Beyond",
        "Two Gun Pete",
        "Epona",
        "Aganju",
        "Chimney Wallstop",
        "Krash Wanderford",
        "Orella Abadon",
        "Sarius",
        "Gorth",
        "Fina Voxom",
        "Alva the Crusher",
        "Isgald Vorst",
        "Alfredo",
        "Relenor Cleaver",
        "Edith Emberstar",
        "Flagulon Reine",
        "Bertrol Gobson",
        "Katrelba Gobson",
        "Cutter Brieze",
        "Palidon Rakk",
        "Quora Towershead",
        "Jini Guise",
        "Helmet Kharafax",
        "Hugo Strongsword",
        "Ajax Lightfoot",
        "Captain Katie",
        "Marisol Contuma",
        "Sola Ranjell",
        "Whistling Damon",
        "Witch of Warwick",
        "Kotriphus Bayne",
        "Liza Fox",
        "Trapp Falloway",
        "Xulax Nightwind",
        "Larissa Kerato",
        "Tatiana Blayde",
        "Venari Heatsmith",
        "Exploding Rats",
        "Lava Launcher",
        "Pelacor Mercenary",
        "Venari Seedsmith",
        "Djinn Biljka",
        "Pelacor Bandit",
        "Venari Wavesmith",
        "Djinn Oshannus",
        "Pelacor Deceiver",
        "Venari Bonesmith",
        "Harklaw",
        "Pelacor Conjurer",
        "Venari Crystalsmith",
        "Djinn Renova",
        "Naga Assassin",
        "Twilight Basilisk",
        "Djinn Chwala",
        "Gargoya Lion",
        "Gargoya Devil",
        "Uraeus",
        "Doctor Blight",
        "Carrion Shade",
        "Riftwing",
        "Shadow Snitch",
        "Crypt Beetle",
        "Silent Sha-vi",
        "Soul Strangler",
        "Life Sapper",
        "Dhampir Stalker",
        "Cursed Windeku",
        "Magi Necrosi",
        "Insidious Warlock",
        "Weirding Warrior",
        "Djinn Muirat",
        "Corpse Fiend",
        "Mycelic Morphoid",
        "Venari Knifer",
        "Venari Scout",
        "Hill Giant",
        "Goblin Psychic",
        "Mycelic Slipspawn",
        "Regal Peryton",
        "Goblin Tower",
        "Mycelic Infantry",
        "Grund",
        "Hunter Jarx",
        "Acid Shooter",
        "Queen Mycelia",
        "Fungus Fiend",
        "Hardy Stonefish",
        "Kulu Swimhunter",
        "Cruel Sethropod",
        "Flying Squid",
        "Deeplurker",
        "Angelic Mandarin",
        "Merdaali Guardian",
        "Diemonshark",
        "River Nymph",
        "Nerissa Tridawn",
        "Wave Brood",
        "Igor Darkspear",
        "River Hellondale",
        "Torrent Fiend",
        "Radiated Scorcher",
        "Lava Spider",
        "Radiated Brute",
        "Scavo Chemist",
        "Antoid Platoon",
        "Scavo Firebolt",
        "Tenyii Striker",
        "Djinn Apprentice",
        "Molten Ash Golem",
        "Forgotten One",
        "Tusk the Wide",
        "Djinn Inferni",
        "Ifrit Rising",
        "Scorch Fiend",
        "Gargoya Scrapper",
        "Sunkai Harvester",
        "Stitch Leech",
        "Blinding Reflector",
        "Chaos Knight",
        "Celestial Harpy",
        "Time Mage",
        "Portal Spinner",
        "Pelacor Arbalest",
        "Temporal Master",
        "Prismologist",
        "Dax Paragon",
        "Adelade Brightwing",
        "Soul Fiend",
        "Supply Runner",
        "Scavo Hireling",
        "Disintegrator",
        "Chaos Agent",
        "Xenith Archer",
        "Xenith Monk",
        "Venari Spellsmith",
        "Magi of Chaos",
        "Gem Meteor",
        "Legionnaire Alvar",
        "Chaos Dragon",
        "Desert Dragon",
        "Zyvax Vuul",
        "Void Dragon",
        "Kelya Frendul",
        "Thaddius Brood",
        "Obsidian",
        "Tarsa",
        "General Sloan",
        "Quix the Devious",
        "Baakjira",
        "Uriel the Purifier",
        "Lira the Dark",
        "Iza the Fanged",
        "Grum Flameblade",
        "Spirit Hoarder",
        "Waka Spiritblade",
        "Carnage Titan"
    ];
    let changeEvent = null;
    const filterCards = () => {
        const cards = 'https://api2.splinterlands.com/market/for_rent_grouped';

    };
    const filterElement = (identifier, placeholder) => {
        const li = document.createElement('li');
        li.innerHTML = '<div class="pl-20 pr-20 pb-10">\n' +
            '\t\t<div class="input-group" style="display: flex;">\n' +
            '\t\t\t<div class="has-feedback has-feedback-left" style="flex-grow: 1;">\n' +
            '\t\t\t\t<input type="search" placeholder="' + placeholder + '" id="pmf_' + identifier + '" class="form-control">\n' +
            '\t\t\t\t<div  class="form-control-feedback">\n' +
            '\t\t\t\t\t<i class="icon-medal-star text-size-base text-muted"></i>\n' +
            '\t\t\t\t</div>\n' +
            '\t\t\t</div>\n' +
            '\t\t</div>\n' +
            '\t</div>';
        return li;
    };
    const addEvents = (identifier) => {
        const element = document.querySelector('#pmf_' + identifier);
        if(element===null)
            return;
        element.addEventListener('change', () => {
            if(changeEvent!==null)
                clearInterval(changeEvent);
            changeEvent = setInterval(filterCards, 2000);
        });
    };
    const addCPFilters = () => {
        const levelFilter = document.querySelector('.category-content > ul > li:nth-child(5)');
        levelFilter.before(filterElement('min_cp', 'Minimal CP'));
        levelFilter.before(filterElement('max_cp', 'Max CP'));

        addEvents('min_cp');
        addEvents('max_cp');
    };
    addCPFilters();
})();